### ISSUE TITLE
Error constructor

### ISSUE THREAD

**Issue by krsaedan** [stegano/winston-s3-transport#1]
hi, i have this error:

TypeError: winston_s3_transport_1.default is not a constructor

code:

// Example - `src/utils/logger.ts`
import winston from "winston";
import S3Transport from "winston-s3-transport";
import { format } from "date-fns";

export const s3Transport = new S3Transport({
  s3ClientConfig: {
    region: "ap-northeast-2",
  },
  s3TransportConfig: {
    bucket: "my-bucket",
    group: (logInfo: any) => {
      // Group logs with `userId` value and store them in memory. 
      // If the 'userId' value does not exist, use the `anonymous` group.
      return logInfo?.message?.userId || "anonymous";
    },
    bucketPath: (groupId: string = "default") => {
      const date = new Date();
      const timestamp = format(date, "yyyyMMddhhmmss");
      // The bucket path in which the log is uploaded. 
      // You can create a bucket path by combining `groupId`, `timestamp`, and `uuid` values.
      return `/logs/${groupId}/${timestamp}/test.log`;
    },
  },
});

    "winston-s3-transport": "^1.1.0"

**Comment by stegano** [comment]
Hi @krsaedan,

Thanks for your report.

I'll check now

**Comment by krsaedan** [comment]
hi, now:

`S3TransportConfig.groupId` has been deprecated. Please use `S3TransportConfig.group` :D

![imagen](https://github.com/stegano/winston-s3-transport/assets/77971873/398013a2-705a-4747-9797-b6e954e65610)

**Comment by stegano** [comment]
@krsaedan 

I just updated It to v1.1.2. Could you try again?

```
npm I winston-s3-transport -S
```

If your issue is resolved, please close this issue. 

Thank you 😊

**Comment by stegano** [comment]
@all-contributors please add @krsaedan for bug

**Comment by krsaedan** [comment]
it works now, thanks!!!

**Comment by stegano** [comment]
This issue has been resolved. I'll close this issue. 
Thank you 🙏
